# Generated by Django 3.0.5 on 2020-12-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=30), verbose_name='URL'),
        ),
    ]
