# Generated by Django 3.0.5 on 2020-12-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
